name: GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *' # Daily at At 00:00 - https://crontab.guru/daily
  workflow_dispatch:

jobs:
  build:
    name: Update README with recent GitHub Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
